fragment SiteParts on Site {
  __typename
  brand {
    __typename
    name
    group
    legal
    tagline
  }
  nav {
    __typename
    links {
      __typename
      label
      href
    }
    cta {
      __typename
      label
      href
    }
  }
  hero {
    __typename
    title
    accents
    script
    sub
    ctaPrimary {
      __typename
      label
      href
    }
    ctaSecondary {
      __typename
      label
      href
    }
    tiles {
      __typename
      label
      note
    }
  }
  marquee
  works {
    __typename
    label
    title
    intro
    items {
      __typename
      src
      brand
      piece
      desc
    }
  }
  services {
    __typename
    label
    title
    items {
      __typename
      n
      slug
      name
      body
      photo
      detail {
        __typename
        claim
        intro
        bullets
        gallery {
          __typename
          src
          alt
        }
      }
    }
  }
  stats {
    __typename
    label
    title
    items {
      __typename
      value
      label
    }
  }
  statement {
    __typename
    small
    big
    accents
  }
  process {
    __typename
    label
    title
    steps {
      __typename
      n
      title
      body
    }
  }
  cta {
    __typename
    title
    body
    button {
      __typename
      label
      href
    }
  }
  agenda {
    __typename
    label
    title
    script
    intro
    slots
    email
    disclaimer
  }
  footer {
    __typename
    columns {
      __typename
      title
      links {
        __typename
        label
        href
      }
    }
    note
  }
}
